apiVersion: apps/v1
kind: Deployment
metadata:
  name: kulu
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kulu
      app.kubernetes.io/tier: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kulu
        app.kubernetes.io/tier: backend
    spec:
      containers:
        - image: timkatee/kulu:0.0.1-alpha
          imagePullPolicy: Always
          name: kulu-backend
          ports:
            - containerPort: 4000
              name: kulu-http-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DB_HOST
                  name: kulu-cm
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DB_PORT
                  name: kulu-cm
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: DB_PASSWORD
                  name: kulu-secrets



