{{- if .Values.ingress.enabled}}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/component: controller
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx


---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lord-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: minikube.internal.kulu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kulu-svc
                port:
                  number: 80
  tls:
    - hosts:
        - minikube.internal.kulu
      secretName: kulu-tls-secret

  {{- end}}