apiVersion: v1
kind: Service
metadata:
  name: kulu-svc
  labels:
    name: kulu
    tier: service
spec:
  selector:
    app.kubernetes.io/name: kulu
    app.kubernetes.io/tier: backend
  ports:
    - port: 80
      protocol: TCP
      targetPort: kulu-http-port